name: Personal Portfolio Preview Deployment

env: 
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - master


jobs: 
  Deploy_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo  
        uses: actions/checkout@v3


      - name: NPM install  Dependencies
      - run: npm install
            
      - name: NPM INSTALL GLOBAL CLI 
      - run: npm install -g vercel 

      - name: pull vercel environment Information
      - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: BUILD project artifacts
      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}


      - name: deploy project artifacts
      - run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}



